"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 15:28:32.055390

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_note_kind"), ["kind"], unique=False)

    op.create_table(
        "habit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("highlight", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("habit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_habit_category_id"), ["category_id"], unique=False)

    op.create_table(
        "dailyentry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("habit_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("count_done", sa.Integer(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["habit_id"],
            ["habit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("habit_id", "date"),
    )
    with op.batch_alter_table("dailyentry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dailyentry_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_dailyentry_habit_id"), ["habit_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dailyentry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dailyentry_habit_id"))
        batch_op.drop_index(batch_op.f("ix_dailyentry_date"))

    op.drop_table("dailyentry")
    with op.batch_alter_table("habit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_habit_category_id"))

    op.drop_table("habit")
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_note_kind"))

    op.drop_table("note")
    op.drop_table("category")
    # ### end Alembic commands ###
