"""app_user

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 16:17:32.243439

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_app_user_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_user_username"))

    op.drop_table("app_user")
    # ### end Alembic commands ###
